# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-20 02:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('manhost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosts.HostManage', verbose_name='管理的主机')),
            ],
        ),
    ]
