# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-23 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
        ('hosts', '0002_userlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='roles',
            field=models.ManyToManyField(to='rbac.Role', verbose_name='拥有的角色'),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='password',
            field=models.CharField(max_length=64, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='username',
            field=models.CharField(max_length=32, verbose_name='用户名'),
        ),
    ]
