# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-23 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0003_auto_20181123_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='emails',
            field=models.EmailField(default='ab@qq.com', max_length=32, verbose_name='邮件'),
            preserve_default=False,
        ),
    ]
