# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-23 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='名称')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='URL别名')),
                ('url', models.CharField(max_length=32, verbose_name='URL')),
                ('is_menu', models.BooleanField(default=False, verbose_name='是否是菜单')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='名称')),
                ('permissions', models.ManyToManyField(blank=True, to='rbac.Permission', verbose_name='拥有的权限')),
            ],
        ),
    ]
